version: "3.9"

services:
  email:
    image: gessnerfl/fake-smtp-server:latest
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.dcm-infrastructure-email.loadbalancer.server.port=8080"
        - "traefik.http.routers.dcm-infrastructure-email.entrypoints=web"
        - "traefik.http.routers.dcm-infrastructure-email.rule=Host(`email.localhost`)"

      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - swarm

networks:
  swarm:
    external: true
