version: "3.9"
# https://elk-docker.readthedocs.io/
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - logging
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.1
    depends_on:
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - logging
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    depends_on:
      - logstash
    ports:
      - 5601:5601
    networks:
      - logging
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

networks:
  logging:
    driver: overlay
