version: "3.9"

services:
  proxy:
    image: dcm-proxy:latest
    command:
      - "--log.level=DEBUG"
      - "--accessLog=true"
      - "--accessLog.format=json"
      - "--accessLog.filePath=/var/log/traefik/access.log.json"
      - "--api.insecure=true"
      - "--api.dashboard=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.watch=true"

      - "--entryPoints.web.address=:80"
      - "--entryPoints.webSecure.address=:443"

      - "--certificatesResolvers.letsEncrypt.acme.email=support@conceptual.ca"
      - "--certificatesResolvers.letsEncrypt.acme.storage=/letsEncrypt/acme.json"
      - "--certificatesResolvers.letsEncrypt.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.letsEncrypt.acme.caServer=https://acme-staging-v02.api.letsEncrypt.org/directory"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.dcm-infrastructure-proxy.loadbalancer.server.port=8080"
        - "traefik.http.routers.dcm-infrastructure-proxy.entrypoints=web"
        - "traefik.http.routers.dcm-infrastructure-proxy.rule=Host(`proxy.localhost`)"

    networks:
      - swarm

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  swarm:
    name: swarm
    external: true
