version: "3.9"

services:
  proxy:
    image: dcm-proxy:latest
    command:
      - "--log.level=DEBUG"
      - "--accessLog=true"
      - "--accessLog.format=json"
      - "--accessLog.filePath=/var/log/traefik/access.log.json"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--api.disabledashboardad=true"

      - "--providers.swarm=true"
      - "--providers.swarm.exposedByDefault=false"
      - "--providers.swarm.watch=true"
      - "--providers.swarm.refreshSeconds=30"

      - "--entryPoints.web.address=:80"

      - "--tracing.elastic=true"
      #- "--tracing.elastic.secrettoken=${}"
      - "--tracing.elastic.serverurl=elasticsearch:9200"
      - "--tracing.elastic.serviceenvironment=dev"

    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        mode: host

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.dcm-infrastructure-proxy.loadbalancer.server.port=8080"
        - "traefik.http.routers.dcm-infrastructure-proxy.entrypoints=web"
        - "traefik.http.routers.dcm-infrastructure-proxy.rule=Host(`proxy.localhost`)"

    networks:
      - swarm

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  swarm:
    name: swarm
    external: true
