version: "3.9"

services:
  dns:
    image: dcm-dnsmasq:latest
    networks:
      - ingress
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - 5380:8080
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=admin

networks:
  ingress:
    name: ingress
    external: true
