version: "3.9"

services:
  dns:
    image: dcm-dnsmasq:latest
    networks:
      - swarm
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 8080
        published: 5380
        mode: host
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=admin

networks:
  swarm:
    name: swarm
    external: true
