name: Create release pull request when version changes

on:
  push:
    branches:
      - "main"
      - "master"
      - "v/*"

jobs:
  build:
    uses: cpdevtools/common-github-workflows/.github/workflows/create-release-pull-request.yml@main
