name: Publish

on:
  push:
    branches:
      - "release/*"

jobs:
  build:
    uses: cpdevtools/common-github-workflows/.github/workflows/pnpm-publish.yml@main
    with:
      toNpm: true
      toGithub: true
      githubToken: ${{ github.token }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
